sudo: required
services:
  - docker
before_install:
  - docker build -t dougsleite/docker-react -f Dockerfile.dev .
script:
  - docker run dougsleite/docker-react npm run -e CI=true test -- --coverage